### ISSUE TITLE
Docs failed to build for 0.2.5.

### ISSUE THREAD

**Issue by mitchmindtree** [RustAudio/coreaudio-sys#40]
I recently added the following to the `Cargo.toml` in the hope of fixing `coreaudio-sys` on docs.rs:

```toml
[package.metadata.docs.rs]
all-features = true
default-target = "x86_64-apple-darwin"
targets = ["x86_64-apple-darwin", "x86_64-apple-ios"]
```

However it appears that, while our CI [can successfully build the docs](https://github.com/RustAudio/coreaudio-sys/runs/806799361?check_suite_focus=true) for `x86_64-apple-darwin`, the [docs.rs build system cannot](https://docs.rs/crate/coreaudio-sys/0.2.5/builds/264503). The docs.rs build fails with:

```
[INFO] [stderr] coreaudio.h:1:10: fatal error: 'AudioToolbox/AudioToolbox.h' file not found
```

Our github docs-check action looks like this:

```yml
  # Build the docs with all features to make sure docs.rs will work.
  macos-docs:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install llvm and clang
      run: brew install llvm
    - name: Install stable
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: cargo doc - all features
      run: cargo doc --all-features --verbose
```

Perhaps we need to tell docs.rs how to do the "install llvm and clang" step somehow?

I don't have time to dig deeper into this right now, but thought I'd open this in case anyone else has some ideas.
